package logstorage

import (
	"fmt"
	"sync"

	"github.com/VictoriaMetrics/VictoriaMetrics/lib/logger"
)

// filterPatternMatch filters field entries by the given pattern, which could be generated by collapse_nums pipe.
//
// See https://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe
type filterPatternMatch struct {
	funcName string
	pm       *patternMatcher

	tokensOnce   sync.Once
	tokens       []string
	tokensHashes []uint64
}

func newFilterPatternMatch(fieldName, funcName string, pm *patternMatcher) *filterGeneric {
	fp := &filterPatternMatch{
		funcName: funcName,
		pm:       pm,
	}
	return newFilterGeneric(fieldName, fp)
}

func (fp *filterPatternMatch) String() string {
	return fmt.Sprintf("%s(%s)", fp.funcName, quoteTokenIfNeeded(fp.pm.String()))
}

func (fp *filterPatternMatch) getTokens() []string {
	fp.tokensOnce.Do(fp.initTokens)
	return fp.tokens
}

func (fp *filterPatternMatch) getTokensHashes() []uint64 {
	fp.tokensOnce.Do(fp.initTokens)
	return fp.tokensHashes
}

func (fp *filterPatternMatch) initTokens() {
	var a []string

	separators := fp.pm.separators

	switch fp.pm.pmo {
	case patternMatcherOptionAny:
		if len(separators) == 1 {
			sep := skipFirstToken(separators[0])
			sep = skipLastToken(sep)
			a = append(a, sep)
			separators = nil
			break
		}

		sep := skipFirstToken(separators[0])
		if sep != "" && isSpecialNumStart(sep[len(sep)-1]) {
			sep = skipLastToken(sep)
		}
		a = append(a, sep)
		separators = separators[1:]

		if len(separators) > 0 {
			sep := skipLastToken(separators[len(separators)-1])
			if sep != "" && isSpecialNumEnd(sep[0]) {
				sep = skipFirstToken(sep)
			}
			a = append(a, sep)
			separators = separators[:len(separators)-1]
		}
	case patternMatcherOptionFull:
		if len(separators) == 1 {
			a = append(a, separators[0])
			separators = nil
			break
		}

		sep := separators[0]
		if sep != "" && isSpecialNumStart(sep[len(sep)-1]) {
			sep = skipLastToken(sep)
		}
		a = append(a, sep)
		separators = separators[1:]

		if len(separators) > 0 {
			sep := separators[len(separators)-1]
			if sep != "" && isSpecialNumEnd(sep[0]) {
				sep = skipFirstToken(sep)
			}
			a = append(a, sep)
			separators = separators[:len(separators)-1]
		}
	case patternMatcherOptionPrefix:
		if len(separators) == 1 {
			sep := skipLastToken(separators[0])
			a = append(a, sep)
			separators = nil
			break
		}

		sep := separators[0]
		if sep != "" && isSpecialNumStart(sep[len(sep)-1]) {
			sep = skipLastToken(sep)
		}
		a = append(a, sep)
		separators = separators[1:]

		if len(separators) > 0 {
			sep := skipLastToken(separators[len(separators)-1])
			if sep != "" && isSpecialNumEnd(sep[0]) {
				sep = skipFirstToken(sep)
			}
			a = append(a, sep)
			separators = separators[:len(separators)-1]
		}
	case patternMatcherOptionSuffix:
		if len(separators) == 1 {
			sep := skipFirstToken(separators[0])
			a = append(a, sep)
			separators = nil
			break
		}

		sep := skipFirstToken(separators[0])
		if sep != "" && isSpecialNumStart(sep[len(sep)-1]) {
			sep = skipLastToken(sep)
		}
		a = append(a, sep)
		separators = separators[1:]

		if len(separators) > 0 {
			sep := separators[len(separators)-1]
			if sep != "" && isSpecialNumEnd(sep[0]) {
				sep = skipFirstToken(sep)
			}
			a = append(a, sep)
			separators = separators[:len(separators)-1]
		}
	default:
		logger.Panicf("BUG: unexpected pmo=%d", fp.pm.pmo)
	}

	for _, sep := range separators {
		if sep != "" && isSpecialNumEnd(sep[0]) {
			sep = skipFirstToken(sep)
		}
		if sep != "" && isSpecialNumStart(sep[len(sep)-1]) {
			sep = skipLastToken(sep)
		}
		a = append(a, sep)
	}

	fp.tokens = tokenizeStrings(nil, a)
	fp.tokensHashes = appendTokensHashes(nil, fp.tokens)
}

func (fp *filterPatternMatch) matchRowByField(fields []Field, fieldName string) bool {
	v := getFieldValueByName(fields, fieldName)
	return fp.pm.Match(v)
}

func (fp *filterPatternMatch) applyToBlockResultByField(br *blockResult, bm *bitmap, fieldName string) error {
	c := br.getColumnByName(fieldName)
	if c.isConst {
		v := c.valuesEncoded[0]
		if !fp.pm.Match(v) {
			bm.resetBits()
		}
		return nil
	}
	if c.isTime {
		return fp.matchColumnGeneric(br, bm, c)
	}

	switch c.valueType {
	case valueTypeString:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeDict:
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		for _, v := range c.dictValues {
			c := byte(0)
			if fp.pm.Match(v) {
				c = 1
			}
			bb.B = append(bb.B, c)
		}
		valuesEncoded, err := c.getValuesEncoded(br)
		if err != nil {
			return err
		}
		bm.forEachSetBit(func(idx int) bool {
			n := valuesEncoded[idx][0]
			return bb.B[n] == 1
		})
	case valueTypeUint8:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeUint16:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeUint32:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeUint64:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeInt64:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeFloat64:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeIPv4:
		return fp.matchColumnGeneric(br, bm, c)
	case valueTypeTimestampISO8601:
		return fp.matchColumnGeneric(br, bm, c)
	default:
		logger.Panicf("FATAL: unknown valueType=%d", c.valueType)
	}
	return nil
}

func (fp *filterPatternMatch) matchColumnGeneric(br *blockResult, bm *bitmap, c *blockResultColumn) error {
	values, err := c.getValues(br)
	if err != nil {
		return err
	}
	bm.forEachSetBit(func(idx int) bool {
		return fp.pm.Match(values[idx])
	})
	return nil
}

func (fp *filterPatternMatch) applyToBlockSearchByField(bs *blockSearch, bm *bitmap, fieldName string) error {
	// Verify whether fp matches const column
	v, err := bs.getConstColumnValue(fieldName)
	if err != nil || v != "" {
		if !fp.pm.Match(v) {
			bm.resetBits()
		}
		return err
	}

	// Verify whether fp matches other columns
	ch, err := bs.getColumnHeader(fieldName)
	if err != nil || ch == nil {
		// Fast path - there are no matching columns.
		if !fp.pm.Match("") {
			bm.resetBits()
		}
		return err
	}

	tokens := fp.getTokensHashes()

	switch ch.valueType {
	case valueTypeString:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		return visitValues(bs, ch, bm, func(v string) bool {
			return fp.pm.Match(v)
		})
	case valueTypeDict:
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		for _, v := range ch.valuesDict.values {
			c := byte(0)
			if fp.pm.Match(v) {
				c = 1
			}
			bb.B = append(bb.B, c)
		}
		return matchEncodedValuesDict(bs, ch, bm, bb.B)
	case valueTypeUint8:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toUint8String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeUint16:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toUint16String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeUint32:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toUint32String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeUint64:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toUint64String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeInt64:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toInt64String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeFloat64:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toFloat64String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeIPv4:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toIPv4String(bs, bb, v)
			return fp.pm.Match(s)
		})
	case valueTypeTimestampISO8601:
		matches, err := matchBloomFilterAllTokens(bs, ch, tokens)
		if err != nil || !matches {
			bm.resetBits()
			return err
		}
		bb := bbPool.Get()
		defer bbPool.Put(bb)
		return visitValues(bs, ch, bm, func(v string) bool {
			s := toTimestampISO8601String(bs, bb, v)
			return fp.pm.Match(s)
		})
	default:
		logger.Panicf("FATAL: %s: unknown valueType=%d", bs.partPath(), ch.valueType)
	}
	return nil
}
